#!/bin/bash
pandoc -o lecture01.html -c db-simple.css -B header.html --title-prefix="Getting Started" lecture01.txt
scp lecture01.html  campbell@bear.cs.dartmouth.edu:public_html/cs65/lecture01/.
sleep 1
scp -r .  campbell@bear.cs.dartmouth.edu:public_html/cs65/lecture01/